In [6]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [7]:
headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'} 
url='https://www.ambitionbox.com/list-of-companies?campaign=desktop_nav'
webpage=requests.get(url,headers=headers)

In [8]:
webpage

In [9]:
soup=BeautifulSoup(webpage.content,'html.parser')

In [10]:
company=soup.find_all('div',class_="companyCardWrapper")

In [11]:
len(company)

20

In [12]:
name=[]
rating=[]
about=[]
salaries=[]


for i in company:
    name.append(i.find('h2').text.strip())
    rating.append(i.find('div',class_="rating_text").text.strip())
    about.append(i.find('span',class_="companyCardWrapper__interLinking").text.strip())
    salaries.append(i.find('span',class_="companyCardWrapper__ActionCount").text.strip())

df=pd.DataFrame({"Name":name,"Rating":rating,"About":about,"Salaries":salaries})
df

,Name,Rating,About,Salaries
0,TCS,3.3,IT Services & Consulting | Bangalore / Bengalu...,1.1L
1,Accenture,3.7,IT Services & Consulting | Bangalore / Bengalu...,70.9k
2,Wipro,3.6,IT Services & Consulting | Hyderabad / Secunde...,62.9k
3,Cognizant,3.6,IT Services & Consulting | Hyderabad / Secunde...,59.8k
4,Capgemini,3.7,IT Services & Consulting | Bangalore / Bengalu...,51.4k
5,HDFC Bank,3.8,Banking | Mumbai +1817 other locations,50.4k
6,Infosys,3.5,IT Services & Consulting | Bangalore / Bengalu...,47.1k
7,ICICI Bank,4.0,Banking | Mumbai +1436 other locations,45.1k
8,HCLTech,3.4,IT Services & Consulting | Chennai +226 other ...,44.3k
9,Tech Mahindra,3.4,IT Services & Consulting | Hyderabad / Secunde...,42.3k
10,Genpact,3.6,IT Services & Consulting | Hyderabad / Secunde...,40.6k
11,Teleperformance,3.8,BPO | Mumbai +254 other locations,36.4k
12,Axis Bank,3.6,Banking | Mumbai +1497 other locations,32.2k
13,Jio,4.3,Telecom | Mumbai +1866 other locations,31.7k
14,Concentrix Corporation,3.6,BPO | Bangalore / Bengaluru +179 other locations,31.4k
15,Amazon,3.9,Internet | Bangalore / Bengaluru +521 other lo...,30.6k
16,iEnergizer,4.6,BPO | Noida +51 other locations,27.4k
17,Reliance Retail,3.9,Retail | Mumbai +1149 other locations,26.9k
18,LTIMindtree,3.6,IT Services & Consulting | Bangalore / Bengalu...,25.6k
19,IBM,3.9,IT Services & Consulting | Bangalore / Bengalu...,25.3k

In [13]:
df.shape

(20, 4)

In [14]:
final_dfs = []
for page in range(1, 8):
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
    url = f'https://www.ambitionbox.com/list-of-companies?page={page}&campaign=desktop_nav'
    webpage = requests.get(url, headers=headers)
    soup = BeautifulSoup(webpage.content, 'html.parser')
    company = soup.find_all('div', class_="companyCardWrapper")
    
    name = []
    rating = []
    about = []
    salaries = []


    for comp in company:
        name.append(comp.find('h2').get_text(strip=True) if comp.find('h2') else "")
        rating.append(comp.find('div', class_="rating_text").get_text(strip=True) if comp.find('div', class_="rating_text") else "")
        about.append(comp.find('span', class_="companyCardWrapper__interLinking").get_text(strip=True) if comp.find('span', class_="companyCardWrapper__interLinking") else "")
        salaries.append(comp.find('span', class_="companyCardWrapper__ActionCount").get_text(strip=True) if comp.find('span', class_="companyCardWrapper__ActionCount") else "")

    df = pd.DataFrame({"Name": name, "Rating": rating, "About": about, "Salaries": salaries})
    final_dfs.append(df)

final = pd.concat(final_dfs, ignore_index=True)

In [15]:
final.shape

(140, 4)

In [16]:
final

,Name,Rating,About,Salaries
0,TCS,3.3,IT Services & Consulting | Bangalore / Bengalu...,1.1L
1,Accenture,3.7,IT Services & Consulting | Bangalore / Bengalu...,70.9k
2,Wipro,3.6,IT Services & Consulting | Hyderabad / Secunde...,62.9k
3,Cognizant,3.6,IT Services & Consulting | Hyderabad / Secunde...,59.8k
4,Capgemini,3.7,IT Services & Consulting | Bangalore / Bengalu...,51.4k
...,...,...,...,...
135,Nagarjuna Construction Company,4.0,Engineering & Construction | Hyderabad / Secun...,5k
136,Schneider Electric,4.1,Industrial Automation | Bangalore / Bengaluru ...,4.9k
137,Persistent Systems,3.6,IT Services & Consulting | Pune +42 other loca...,4.9k
138,vivo,4.1,Consumer Electronics & Appliances | Noida +414...,4.9k
139,State Bank of India,3.8,Banking | Mumbai +618 other locations,4.9k

In [17]:
final.to_csv('company_data.csv', index=False)